### ISSUE TITLE
Investigate total discrepancy between Ice and AWS bill

### ISSUE THREAD

**Issue by ckelner** [TheWeatherCompany/ice#1]
See: https://github.com/Netflix/ice/issues/143

**Comment by ckelner** [comment]
Written some more on the py script to check ice logic, see: https://github.com/TheWeatherCompany/grid-etc/blob/master/cloud-provider-scripts-tools/AWS/consolidated_billing/aws_csv_reader.py

So far everything is totalling up correctly still.

**Comment by ckelner** [comment]
Yeah... so... pretty sure it happens to be this:

> "If different accounts have different AZ mappings, you will also need to subclass BasicAccountService and override method getAccountMappedZone to provide correct AZ mapping."

**Comment by ckelner** [comment]
Turns out that the method `getAccountMappedZone` doesn't seem to exist... so wtf.

**Comment by ckelner** [comment]
Asked about documentation issue here: https://github.com/Netflix/ice/issues/144

**Comment by ckelner** [comment]
Looking at https://github.com/Netflix/ice/blob/master/src/java/sample.properties#L75-L79

``` properties
# set reservation owner accounts. "ice.owneraccount.account2=account3,account4" means reservations in account2 can be shared by account3 and account4
# if reservation capacity poller is enabled, the poller will try to poll reservation capacity through ec2 API (desribeReservedInstances) for each reservation owner account.
ice.owneraccount.account1=
ice.owneraccount.account2=account3,account4
ice.owneraccount.account5=account6
```

it seems that we should have every account referencing every other account.  Which seems artificially arduous.  I am going to attempt it and see what happens.

Then looking at https://github.com/Netflix/ice/blob/master/src/java/sample.properties#L81-L84

``` properties
# if reservation capacity poller needs to use IAM role to access ec2 API, set the assumed role here for each reservation owner account
ice.owneraccount.account1.role=ice
ice.owneraccount.account2.role=ice
ice.owneraccount.account5.role=ice
```

it appears that we should have a role in every account for ice to access?  Again, seems cumbersome...

**Comment by ckelner** [comment]
Regarding owner accounts, I've tried the following but it doesn't seem to have changing anything for us, I've tried it both as account numbers and as the naming convention defined earlier in the config (as seen below):

``` properties
<redacted>
```

**Comment by packplusplus** [comment]
Pretty sure I see a typo in there...
j/k

**Comment by ckelner** [comment]
Data sent over to the Netflix folks:

In ice it reports usage as:

```
OndemandInstances   1,261.00 
ReservedInstancesHeavy  24,469.00
```

![screen shot 2015-02-11 at 7 46 35 pm](https://cloud.githubusercontent.com/assets/133862/6160551/4d596b6e-b232-11e4-8855-64e8a799a652.png)

I'm not sure how far I can trust the AWS Billing Console since I think the way it displays the data is different from the csv.  Since I can't manipulate the full csv (17million lines, 6gb in side), I had to trim it down to a single account with the following commands:

``` shell
grep -E '123456' ~/kelner_temp/98765-aws-billing-detailed-line-items-with-resources-and-tags-2015-01.csv > account.csv
```

where `123456` is the account number we are after
then:

``` shell
grep -E 'RunInstances' account.csv > account_instances.csv
```

Then I manually removed data transfer costs by sorting the data in the sheet.  I found the following:

```
total usage reserved:  25618  
total usage on demand:  1261  
```

![screen shot 2015-02-11 at 9 01 08 pm](https://cloud.githubusercontent.com/assets/133862/6160701/a70dc43c-b234-11e4-8b10-7a31c73d88c2.png)

The formula used for that is:
`=SUMIFS(M2:M25744, I2:I25744, "Y")` and `=SUMIFS(M2:M25744, I2:I25744, "N")`

I did notice these sort of weird "no zone" entries in the sheet though:
![screen shot 2015-02-11 at 9 02 19 pm](https://cloud.githubusercontent.com/assets/133862/6160724/f86c5c62-b234-11e4-8341-8dd3b8c069e1.png)
![screen shot 2015-02-11 at 9 02 47 pm](https://cloud.githubusercontent.com/assets/133862/6160726/fc733f42-b234-11e4-9bae-12e1992c93f8.png)

And then this weird "RunInstance:0002" sort of thing under operation?
![screen shot 2015-02-11 at 9 03 45 pm](https://cloud.githubusercontent.com/assets/133862/6160729/00d33aa6-b235-11e4-927b-3750f1e5cbb8.png)

I wonder if either of those latter weird entries is causing problems?

I'll continue to dig down into each instance type.

Additionally there is are about 5,000 lines that simply look like this:
![screen shot 2015-02-11 at 9 48 45 pm](https://cloud.githubusercontent.com/assets/133862/6160959/debbc566-b237-11e4-848e-e79394e57f7a.png)

Where normally it seems that the "Usage Type" column contains the machine type in question, and in these ~5000 lines there is no machine type.

I figured out what the "HeavyUsage" without the machine type is, seems you have to look in description column for those:
![screen shot 2015-02-11 at 10 46 26 pm](https://cloud.githubusercontent.com/assets/133862/6161510/f4a41128-b23f-11e4-9d78-b075de5e2115.png)

And the empty AZ entries
![screen shot 2015-02-11 at 10 54 13 pm](https://cloud.githubusercontent.com/assets/133862/6161581/05b80edc-b241-11e4-9d3f-436bcbb4fee9.png)
 I'm not quite so clear on, but more info in the description field:

Getting the unique "usageType" from the csv, I used the advanced filter in excel, so I end up with:

```
BoxUsage:m1.large
BoxUsage:t2.micro
BoxUsage:t2.small
HeavyUsage:m1.small
HeavyUsage:c1.xlarge
HeavyUsage:m1.large
HeavyUsage:m1.xlarge
HeavyUsage:m2.2xlarge
HeavyUsage:r3.2xlarge
HeavyUsage:t2.micro
```

Totaling them up I get:

```
BoxUsage:m1.large           288
BoxUsage:t2.micro           539
BoxUsage:t2.small           434
HeavyUsage:m1.small         3720
HeavyUsage:c1.xlarge        744
HeavyUsage:m1.large         1944
HeavyUsage:m1.xlarge        13797
HeavyUsage:m2.2xlarge       4464
HeavyUsage:r3.2xlarge       744
HeavyUsage:t2.micro         205

Total                       26879
```

When compared to ice:
![screen shot 2015-02-11 at 10 41 22 pm](https://cloud.githubusercontent.com/assets/133862/6161454/22ea6204-b23f-11e4-8bde-3f1d29e398b3.png)

```
aggregated          25,730.00
c1.xlarge.windows   744.00
m1.large            1,488.00    
m1.large.windows    744.00
m1.small            3,720.00    
m1.xlarge           13,392.00   
m2.2xlarge          3,720.00    
r3.2xlarge          744.00  
t2.micro            744.00  
t2.small            434.00
```

To save some time I lumped together windows from ice, and heavy/on-demand from aws for the time being just to make things easier (I know the cost isn't the same, but just so I can see how the numbers add up):

```
ice  :  c1.xlarge           744
aws  :  c1.xlarge           744
ice  :  m1.large            2,232
aws  :  m1.large            2,232
ice  :  m1.small            3,720
aws  :  m1.small            3,720
ice  :  m1.xlarge           13,392      --- different
aws  :  m1.xlarge           13,797       --- different
ice  :  m2.2xlarge          3,720      --- different
aws  :  m2.2xlarge          4,464      --- different
ice  :  r3.2xlarge          744 
aws  :  r3.2xlarge          744
ice  :  t2.micro            744
aws  :  t2.micro            744
ice  :  t2.small            434
aws  :  t2.small            434
```

**Comment by ckelner** [comment]
Given the data above, it looks like the usage difference is coming from those columns which are missing availability zone.  If I take those usage numbers and add them to the lower values in ice, I get the usage numbers that we expect:
![screen shot 2015-02-12 at 11 19 42 am](https://cloud.githubusercontent.com/assets/133862/6171604/ae1bafbc-b2a9-11e4-89c0-a1bb1bd88e3c.png)

**Comment by ckelner** [comment]
I see now that the empty zone case above gets skipped here: https://github.com/Netflix/ice/blob/master/src/java/com/netflix/ice/basic/BasicLineItemProcessor.java#L299-L300

And I assume processed by the Reservation code later, however I'm having a hard time following the reservation code.  I am still working through it, will update if I figure anything further out.

**Comment by ckelner** [comment]
seeing a lot of this now:

```
2015-02-16 02:46:21,185 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m1.large
2015-02-16 02:46:21,185 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m1.large
2015-02-16 02:46:21,185 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m1.large
2015-02-16 02:46:21,185 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m1.large
2015-02-16 02:46:21,185 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m1.large
2015-02-16 02:46:21,185 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m1.large
2015-02-16 02:46:21,185 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m1.large
2015-02-16 02:46:21,185 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m1.large
2015-02-16 02:46:21,185 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m2.xlarge
2015-02-16 02:46:21,186 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m2.xlarge
2015-02-16 02:46:21,186 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m2.xlarge
2015-02-16 02:46:21,186 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m2.xlarge
2015-02-16 02:46:21,186 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m2.xlarge
2015-02-16 02:46:21,186 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m2.xlarge
2015-02-16 02:46:21,186 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m2.xlarge
2015-02-16 02:46:21,186 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicReservationService  - Not able to find reservation price for us-east-1|m2.xlarge
```

**Comment by ckelner** [comment]
I'm closing this.  My totals are now an even greater percentage off (roughly 20% off now, where-as before they were ~5% off) now, however I have a tangible bug to follow as seen here: https://github.com/Netflix/ice/issues/147

I got to this point by having each of the 70+ accounts reference the other (as they are all under consolidated billing) in the `owneraccount` section of the config.  Then I went to each of the 70+ accounts and added an IAM cross account access role for reservation polling and added each account and role mapping in the `role` section of the config.

These seem to have been the missing pieces for us I think.  I believe resolving https://github.com/Netflix/ice/issues/147 will account for the 20% difference.  If not I'll re-open this issue.

See https://github.com/OSS-TheWeatherCompany/ice/issues/2

**Comment by ckelner** [comment]
Cameron and I looked at past months and factoring in the missing support cost, all the past months are off:
- Sept: +9,000
- Oct: +14,000
- Nov: +0.16
- Dec: +49,000
- Jan: +17,000

**Comment by ckelner** [comment]
We're going to chase two trails, one w/ regards to RI and one w/ regards to billing file processing missing data.

**Comment by ckelner** [comment]
Some interesting instances that get skipped without region that aren't us-east-1 by default:

```
2015-02-20 03:16:39,254 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicLineItemProcessor  - 1c) ignoring item: [Estimated, 013328811177, 216803239211, LineItem, Amazon Elastic Compute Cloud, 3207448, , , EU-HeavyUsage:c3.2xlarge, RunInstances, , Y, USD 0.1349 hourly fee per Linux/UNIX (Amazon VPC), c3.2xlarge instance (3360.0 hours purchased, 2275.00000000 hours used), 2015-02-01 00:00:00, 2015-02-28 23:59:59, 1085.00000000, , 453.260000, , 146.362500000000]
2015-02-20 03:16:39,254 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicLineItemProcessor  - 1c) ignoring item: [Estimated, 013328811177, 216803239211, LineItem, Amazon Elastic Compute Cloud, 3207450, , , EU-HeavyUsage:c3.2xlarge, RunInstances, , Y, USD 0.1349 hourly fee per Linux/UNIX (Amazon VPC), c3.2xlarge instance (4032.0 hours purchased, 2730.00000000 hours used), 2015-02-01 00:00:00, 2015-02-28 23:59:59, 1302.00000000, , 543.920000, , 175.643000000000]
2015-02-20 03:16:39,255 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicLineItemProcessor  - 1c) ignoring item: [Estimated, 013328811177, 682134577783, LineItem, Amazon Elastic Compute Cloud, 3207466, , , EU-HeavyUsage:c3.xlarge, RunInstances, , Y, USD 0.06745 hourly fee per Linux/UNIX (Amazon VPC), c3.xlarge instance (1344.0 hours purchased, 651.00000000 hours used), 2015-02-01 00:00:00, 2015-02-28 23:59:59, 693.00000000, , 90.650000, , 46.7400500000000]
2015-02-20 03:16:39,259 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicLineItemProcessor  - 1c) ignoring item: [Estimated, 013328811177, 682134577783, LineItem, Amazon Elastic Compute Cloud, 2263576, , , USW2-HeavyUsage:m3.2xlarge, RunInstances, , Y, USD 0.12 hourly fee per Linux/UNIX (Amazon VPC), m3.2xlarge instance (672.0 hours purchased, 455.00000000 hours used), 2015-02-01 00:00:00, 2015-02-28 23:59:59, 217.00000000, , 80.640000, , 26.0400000000]
2015-02-20 03:16:39,261 [com.netflix.ice.processor.BillingFileProcessor] ERROR basic.BasicLineItemProcessor  - 1c) ignoring item: [Estimated, 013328811177, 682134577783, LineItem, Amazon Elastic Compute Cloud, 2263576, , , USW2-HeavyUsage:m3.2xlarge, RunInstances, , Y, USD 0.12 hourly fee per Linux/UNIX (Amazon VPC), m3.2xlarge instance (672.0 hours purchased, 455.00000000 hours used), 2015-02-01 00:00:00, 2015-02-28 23:59:59, 217.00000000, , 80.640000, , 26.040000
```

There's around hundred of these. between Jan 01 and now.

**Comment by ckelner** [comment]
Doesn't get picked up later at all:

```
2015-02-20 03:55:14,488 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - cut hours to 671
2015-02-20 03:55:14,488 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - Processing reservations...
2015-02-20 03:55:14,488 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - Utilization LIGHT size is 0, skipping...
2015-02-20 03:55:14,488 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - Processing reservations...
2015-02-20 03:55:14,488 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - Utilization MEDIUM size is 0, skipping...
2015-02-20 03:55:14,488 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - Processing reservations...
2015-02-20 03:55:14,488 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - Utilization HEAVY size is 0, skipping...
2015-02-20 03:55:14,488 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - Processing reservations...
2015-02-20 03:55:14,488 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - Utilization FIXED size is 0, skipping...
```

**Comment by ckelner** [comment]
These skipped line items don't have zones at all.  I opened a ticket with AWS:

```
Hello,

So I've raised this flag previously, but it was due to line items being in the us-east-1a zone.  Now I am seeing several line items which are not in us-east-1 (per the UsageType column).

For example:
InvoiceID,PayerAccountId,LinkedAccountId,RecordType,RecordId,ProductName,RateId,SubscriptionId,PricingPlanId,UsageType,Operation,AvailabilityZone,ReservedInstance,ItemDescription,UsageStartDate,UsageEndDate,UsageQuantity,BlendedRate,BlendedCost,UnBlendedRate,UnBlendedCost,ResourceId,user:Billing,user:Owner
"Estimated","013328811177","682134577783","LineItem","400000000223405011","Amazon Elastic Compute Cloud","3207476",,,"EU-HeavyUsage:r3.large","RunInstances",,"Y","USD 0.0323 hourly fee per Linux/UNIX (Amazon VPC), r3.large instance (1488.0 hours purchased, 1488.0 hours used)","2015-01-01 00:00:00","2015-01-31 23:59:59","0",,"48.060000",,"0",,,
"Estimated","013328811177","682134577783","LineItem","400000000223404865","Amazon Elastic Compute Cloud","2321982",,,"EU-HeavyUsage:r3.large","RunInstances",,"Y","USD 0.034 hourly fee per Linux/UNIX (Amazon VPC), r3.large instance (2232.0 hours purchased, 2232.0 hours used)","2015-01-01 00:00:00","2015-01-31 23:59:59","0",,"75.890000",,"0.00200000000",,,
"Estimated","013328811177","682134577783","LineItem","400000000223404943","Amazon Elastic Compute Cloud","3207476",,,"EU-HeavyUsage:r3.large","RunInstances",,"Y","USD 0.0323 hourly fee per Linux/UNIX (Amazon VPC), r3.large instance (1488.0 hours purchased, 1488.0 hours used)","2015-01-01 00:00:00","2015-01-31 23:59:59","0",,"48.060000",,"0",,,
"Estimated","013328811177","682134577783","LineItem","400000000223404871","Amazon Elastic Compute Cloud","3373535",,,"EU-HeavyUsage:r3.large","RunInstances",,"Y","USD 0.0323 hourly fee per Linux/UNIX (Amazon VPC), r3.large instance (1488.0 hours purchased, 715.00000000 hours used)","2015-01-01 00:00:00","2015-01-31 23:59:59","773.00000000",,"48.060000",,"24.965500000000",,,
"Estimated","013328811177","682134577783","LineItem","400000000223404866","Amazon Elastic Compute Cloud","3259269",,,"EU-HeavyUsage:r3.large","RunInstances",,"Y","USD 0.0323 hourly fee per Linux/UNIX (Amazon VPC), r3.large instance (1488.0 hours purchased, 1488.0 hours used)","2015-01-01 00:00:00","2015-01-31 23:59:59","0",,"48.060000",,"0",,,

Can you explain this to me please?  We need to be able to reconcile these costs outside of the AWS Billing dashboard.

Thank you,
Chris
```

**Comment by ckelner** [comment]
Catching up here -- Feed back from Netflix dev:

`Feb 20, 2015, 1:23 PM EST`

> Lines with no AZ are the totals for the month. If you add them up, you'd be double-counting. That is why Ice ignores them.

My reply:

> Hey thanks for the reply and that bit of info.  I'm just hunting if you will.  Trying to make sense of everything.  I can't figure out where $XX,000 is going w/ the RI poller off, and when I turn on the RI poller it is off by $XXX,000 which is worse :(.  I would hope that w/ the poller on it would be closer.
> 
> I dug back historically all the way to sept last year, and the amount it is off each month is different by quite a lot.  For example, Sept was off in the five figures, while Nov was only off by 0.64 cents, and dec only in the four figures.
> 
> Anyways, I'm just dumping data here as I find it in hopes you can shine light on anything like you just did, but if that is problematic I can stop tracking my debugging attempts here.

My data dump from 3 days ago for the netflix issue:

More information, I've been in touch with AWS support regarding this, because it seems that our ECSV/DBR (as AWS calls it) is wrong if this logic is to be trusted.

Here's my most recent comms with AWS in chronological order, the last two communications are most important, citing specific problems found with the ECSV/DBR.  TL;DR: When adding up every line item (including the "utilization" summarizations we've talked about in this GitHub issue), outside of ice, it equals our consolidated bill total.  When excluding those values it falls short in the same way ice does.

_The Weather Channel
Feb 20, 2015
09:15 AM -0500_

> So I've raised this flag previously, but it was due to line items being in the us-east-1a zone.  Now I am seeing several line items which are not in us-east-1 (per the UsageType column).
> 
> For example:
> 
> ```
> InvoiceID,PayerAccountId,LinkedAccountId,RecordType,RecordId,ProductName,RateId,SubscriptionId,PricingPlanId,UsageType,Operation,AvailabilityZone,ReservedInstance,ItemDescription,UsageStartDate,UsageEndDate,UsageQuantity,BlendedRate,BlendedCost,UnBlendedRate,UnBlendedCost,ResourceId,user:Billing,user:Owner
> "Estimated","redacted","redacted","LineItem","400000000223405011","Amazon Elastic Compute Cloud","3207476",,,"EU-HeavyUsage:r3.large","RunInstances",,"Y","USD 0.0323 hourly fee per Linux/UNIX (Amazon VPC), r3.large instance (1488.0 hours purchased, 1488.0 hours used)","2015-01-01 00:00:00","2015-01-31 23:59:59","0",,"48.060000",,"0",,,
> "Estimated","redacted","redacted","LineItem","400000000223404865","Amazon Elastic Compute Cloud","2321982",,,"EU-HeavyUsage:r3.large","RunInstances",,"Y","USD 0.034 hourly fee per Linux/UNIX (Amazon VPC), r3.large instance (2232.0 hours purchased, 2232.0 hours used)","2015-01-01 00:00:00","2015-01-31 23:59:59","0",,"75.890000",,"0.00200000000",,,
> "Estimated","redacted","redacted","LineItem","400000000223404943","Amazon Elastic Compute Cloud","3207476",,,"EU-HeavyUsage:r3.large","RunInstances",,"Y","USD 0.0323 hourly fee per Linux/UNIX (Amazon VPC), r3.large instance (1488.0 hours purchased, 1488.0 hours used)","2015-01-01 00:00:00","2015-01-31 23:59:59","0",,"48.060000",,"0",,,
> "Estimated","redacted","redacted","LineItem","400000000223404871","Amazon Elastic Compute Cloud","3373535",,,"EU-HeavyUsage:r3.large","RunInstances",,"Y","USD 0.0323 hourly fee per Linux/UNIX (Amazon VPC), r3.large instance (1488.0 hours purchased, 715.00000000 hours used)","2015-01-01 00:00:00","2015-01-31 23:59:59","773.00000000",,"48.060000",,"24.965500000000",,,
> "Estimated","redacted","redacted","LineItem","400000000223404866","Amazon Elastic Compute Cloud","3259269",,,"EU-HeavyUsage:r3.large","RunInstances",,"Y","USD 0.0323 hourly fee per Linux/UNIX (Amazon VPC), r3.large instance (1488.0 hours purchased, 1488.0 hours used)","2015-01-01 00:00:00","2015-01-31 23:59:59","0",,"48.060000",,"0",,,
> ```
> 
> Can you explain this to me please?  We need to be able to reconcile these costs outside of the AWS Billing dashboard.

_Amazon Web Services
Feb 20, 2015
01:27 PM -0500_

> I'm going to submit a feature request to have the AZs reported in this section of the DBR, but I want to clarify a few things as well to help reconcile these costs outside of the AWS Billing dashboard. As I'm sure you may be aware, this section is used to determine whether or not a Reserved Instance has been fully utilized throughout the month and does not come with associated charges. It will give you a basic snapshot of how many hours these RIs are being utilized throughout a given month (which is a good reason why it might be useful to include the AZs as well). To allocate costs, there are a few options you can use, rather than relying on the section you indicated:
> 1. You can allocate the costs to the RI owner
> 2. You can allocate hourly usage by using the unblended rates in the individual line items that are using your RIs
> 
> I will send this feature request to our EC2 team to see if they can include the AZ for this section of your DBR. Thank you for your patience and please let us know if you have any further questions.

_The Weather Channel
Feb 20, 2015
01:59 PM -0500_

> To be certain I want to further clarify what you've stated.
> 
> To me it sounds like these lines are duplicated charges that also appear as LineItems elsewhere.  It sounds like they serve as a means to express underutilized reservations.  Is that correct?
> 
> If that is correct, then can you tell me if there is a line item elsewhere in the CSV that charged 100% of the cost for a reservation month rather than an hourly cost?  The majority of what we have at TWC are HEAVY 3yr which we get charged for regardless of usage.   I need to be able to reconcile full cost.

_Amazon Web Services
Feb 20, 2015
04:28 PM -0500_

> The items that you included in your first email are basically a summary, including the utilization and the total cost at the bottom of your Detailed Billing Report. It is also broken out by the hour. In other words, both the line items and the summary are two ways of expressing your RI utilization. You were not charged twice, but the Detailed Billing Report includes both views to give you both a summary and a more granular view. In the individual line items, you'll be able to see which specific RI was used, which instance it was applied to and which account owned that instance. The summary will express how much the total RI cost, as well as how many hours it was in use throughout the month. 
> 
> Regrading your second question, you should find that information within the line items that you provided. In the example that you provided, for an RI that was 100% utilized, you will see something like "1488.0 hours purchased, 1488.0 hours used." For an RI that was not entirely used, you will see something like "1488.0 hours purchased, 715.00000000 hours used."
> 
> I hope that makes sense. If anything I said wasn't clear, or if you have any further questions, please let us know.

_The Weather Channel
Feb 23, 2015
10:33 AM -0500_

> So this stumps me a little bit... let me explain why.  
> 
> I wrote a very simple python script which takes each row of the csv that includes "LineItem" in the "RecordType" column.  This includes both the "hour-by-hour" charges per account, and the aforementioned "utilization" rows that we discussed earlier in this ticket.  So here's the rub, the total comes out to be the same total that is printed at the end of the bill.
> 
> You can find the py script here: https://gist.github.com/ckelner/962b9e52db11fc73cf68
> 
> Here's a run on our january bill:
> $ python aws_csv_reader.py 013328811177-aws-billing-detailed-line-items-with-resources-and-tags-2015-01.csv 
> Rows processed:  17229196
> LineItem UnBlendedCost total:  XXXXXX.XX <redacted for github>
> 
> And from the AWS billing console it reports: $XXX,XXX.XX <redacted for github>
> 
> So I dug out the "utilization" lines from the csv and created a smaller csv so these could be examined.  That csv can be seen here: <redacted for github> -- as you can see the script I wrote will pick up those line items just fine, and pull the unblended cost for those lines.
> 
> This smaller csv was created using:
> $ head -n 1 013328811177-aws-billing-detailed-line-items-with-resources-and-tags-2015-01.csv > jan_utilization.csv
> $ grep -Eiw 'HeavyUsage.*purchased' ~/kelner_temp/013328811177-aws-billing-detailed-line-items-with-resources-and-tags-2015-01.csv >> jan_utilization.csv 
> 
> Without those values, the total is not correct.
> I wrote a second script (seen here: https://gist.github.com/ckelner/878d653928d476d22fb9) that excludes those line items (as seen in the csv provided from dropbox) from the total.  The total then comes out to:
> 
> $ python aws_csv_reader_v2.py 013328811177-aws-billing-detailed-line-items-with-resources-and-tags-2015-01.csv 
> Rows processed:  17229196
> LineItem UnBlendedCost total:  XXXXXX.XXX <redacted for github>
> 
> So this value is $14,000 off from the correct total.
> 
> So can you help me understand why that is?  As I understand it, counting those "utilization" lines would effectively have me counting resources twice, but given that the total is the same, I don't see how that is possible?

_Amazon Web Services
Feb 23, 2015
04:02 PM -0500_

> Thank you again for reaching out.
> 
> We do want to give a direct, clear and concise answer regarding this to make sure we can figure out the issue and come up with an accurate solution.
> 
> I do apologize for the length of time on this case, but I will coordinate with the first Concierge Agent to properly research and clarify what can be done. So you are aware, we are escalating to our internal Billing Platform service team to make sure we know exactly why this is occurring.
> 
> Any recommendations made by the team will be passed along to you as soon as we receive them.
> 
> We strongly appreciate your patience through this, and please let us know if there is anything further we can assist with at this time.
> 
> Will reach out again soon!

I opened another ticket w/ AWS about their cost explorer where I saw a similar inconsistency: 

_The Weather Channel
Feb 23, 2015
02:30 PM -0500_

> You may also want to reference case #1341404481
> 
> It appears that when viewing the total for reserved instances in the AWS cost explorer, the total is correct as seen in attachment "reserved_jan_2015_total.png" and the total is mismatched (under cost) when viewing by availability zone as seen in attachment "reserved_jan_2015_az.png" for each account under our consolidated bill.
> 
> This correlates to a mismatch we've also seen in our ECSV/DBR (as noted in the other case #1341404481).
> 
> Can you help us understand this?

"reserved_jan_2015_total.png"
![reserved_jan_2015_total](https://cloud.githubusercontent.com/assets/133862/6337562/7173bc44-bb78-11e4-9a11-e0d02ba78368.png)
"reserved_jan_2015_az.png"
![reserved_jan_2015_az](https://cloud.githubusercontent.com/assets/133862/6337565/7ae72f72-bb78-11e4-804d-d22711558453.png)

_Amazon Web Services
Feb 23, 2015
04:02 PM -0500_

> Thank you again for reaching out.
> 
> We do want to give a direct, clear and concise answer regarding this to make sure we can figure out the issue and come up with an accurate solution.
> 
> I do apologize for the length of time on this case, but I will coordinate with the first Concierge Agent to properly research and clarify what can be done. So you are aware, we are escalating to our internal Billing Platform service team to make sure we know exactly why this is occurring.
> 
> Any recommendations made by the team will be passed along to you as soon as we receive them.
> 
> We strongly appreciate your patience through this, and please let us know if there is anything further we can assist with at this time.
> 
> Will reach out again soon!

...

I wrote in the other issue:

> I want to be sure that I make mention that I am **NOT** using the reservation poller.  When I enabled it and _seemingly_ got the configuration correct, my bill was off by a much larger factor (as mentioned earlier in this issue) -- it was off in the 6 digits (~20%) versus the low 5 digits (~3%) without it.  I opened https://github.com/Netflix/ice/issues/147 to work on it, but I was unable to make any progress.  Seeing as 3% was easier to reconcile than 20% I decided to continue working without the RI poller.

...

> By making these changes here: https://github.com/Netflix/ice/compare/master...OSS-TheWeatherCompany:fix-npe-on-bootstrap Our bill is exact for months without credits from AWS.
> 
> Spot checking individual accounts, all cost and utilization adds up except for regions that fall into the logic  > where "no zone" line items get shoved into the "a" zone of a given region.  Other than that everything looks perfect as far as we can tell.

...

From the netflix dev:

> I looked at the code changes. Essentially, you're double-counting in Ice to match AWS [broken?] reporting. Does this resolve the issue?
> From me:
> Hey yes -- I'm waiting to hear back from AWS further regarding the issue.  They've sent it to their billing team in Seattle.  I'll report back what they have to say.  This may in fact be an issue with the DBR somehow.  
> 
> Thank you for following up.

**Comment by ckelner** [comment]
Just a bit more info, I tried an undocumented config option suggested by another Ice user `ice.resourceGroupCost=files` to see if it made any difference with the stock codebase.  It results in the same differences we saw without that configuration option unfortunately.

**Comment by ckelner** [comment]
Going to close this now.  Please reference https://github.com/Netflix/ice/issues/143 for resolution.
